-
  name: "Configure MariaDB server"
  hosts: all
  remote_user: root
  tasks:
  - name: "Copy script files"
    copy:
      src: ./files/{{ item }}
      dest: /tmp/{{ item }}
    loop:
    - mysql-confg.sql
    - db-load-script.sql
  
  - name: "Run scripts"
    ansible.builtin.shell:
      cmd: $(which mysql) < {{ item }}
      chdir: /tmp/
      executable: /usr/bin/bash
    loop:
    - mysql-confg.sql
    - db-load-script.sql
